name: vendasagrindus
description: Aplicacao de forca de vendas da Agrindus

version: 1.4.0+21

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  rflutter_alert: ^2.0.7
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  modal_progress_hud_nsn: ^0.5.1
  animations: ^2.0.11
  intl: ^0.19.0
  collection: ^1.18.0
  darq: ^1.0.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  lottie: ^3.1.0
  flutter_hooks: ^0.20.5
  email_validator: ^2.1.17
  flutter_local_notifications: ^19.5.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.6
  firebase_messaging: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_local_notifications:
    path: ./patches/flutter_local_notifications

flutter:
  uses-material-design: true

  assets:
   - assets/logos/
   - assets/icons/
   - assets/images/
   - assets/animations/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
